default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: vchat_development

test:
  <<: *default
  database: vchat_test

production:
  <<: *default
  database: vchat_production